services:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: local
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend:/go/src/app
    ports:
      - 8080:8080
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: local
      dockerfile: ./build/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    cpu_quota: 70000
