openapi: 3.1.0
info:
  title: tech-blog-tech-blog-summary
  version: 1.0.0

servers:
  - url: "http://localhost:8080"
    description: local dev

paths:
  "/ping":
    get:
      tags:
        - getPing
      operationId: getPing
      responses:
        "200":
          description: get ping success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ping"
        "400":
          description: 不正なリクエストです。
  "/rss":
    get:
      tags:
        - getRss
      operationId: getRss
      responses:
        "200":
          description: get rss success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rss"
        "400":
          description: 不正なリクエストです。

components:
  schemas:
    ping:
      properties:
        message:
          type: string
      required:
        - message
    rss:
      properties:
        title:
          type: string
        link:
          type: string
        description:
          type: string
        lastBuildDate:
          type: string
      required:
        - title
        - link
        - description
        - lastBuildDate