name: backend

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/backend.yml
      - backend/**

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      GO_VERSION: ${{ steps.go.outputs.GO_VERSION }}
    steps:
      - name: Set up golang vars
        id: go
        run: |
          echo "GO_VERSION=1.21.5" >> $GITHUB_OUTPUT
  golangci:
    runs-on: ubuntu-latest
    needs:
      - vars
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.vars.outputs.GO_VERSION }}
          cache: true
          cache-dependency-path: backend/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 1.5.4
          working-directory: ./backend
